[package]
name    = "rustfmt-sort"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
clap         = { workspace = true, features = ["derive", "std"] }
embed-commit = { workspace = true }
quote        = { workspace = true }
syn          = { workspace = true, features = ["full", "parsing", "visit-mut", "extra-traits", "printing"] }
