[package]
name    = "voyager-client-module-cometbls"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy-sol-types             = { workspace = true }
cometbls-light-client-types = { workspace = true, features = ["proto", "ethabi", "serde", "bincode"] }
embed-commit                = { workspace = true }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
macros                      = { workspace = true }
num-bigint                  = { workspace = true }
protos                      = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
unionlabs                   = { workspace = true, features = ["bincode", "bcs"] }
voyager-sdk                 = { workspace = true }
gnark-key-parser            = { workspace = true }


[dev-dependencies]
bcs         = { workspace = true }
hex         = { workspace = true }
hex-literal = { workspace = true }
