[package]
name = "iaviewer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
rusty-leveldb = "4.0.0"

[lints]
workspace = true
