[package]
name    = "mpc-shared"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
hex        = { workspace = true, features = ["alloc"] }
postgrest  = "1.6"
reqwest    = { workspace = true, features = ["json"] }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true, features = ["full"] }
