[package]
name    = "create-voyager-config"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap         = { workspace = true, features = ["derive", "env", "error-context", "help"] }
cliclack     = "0.3.6"
embed-commit = { workspace = true }
ucs04        = { workspace = true }
