[package]
name    = "create-voyager-config"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow               = { workspace = true }
beacon-api-types     = { workspace = true }
chain-kitchen        = { workspace = true }
clap                 = { workspace = true, features = ["derive", "env", "error-context", "help"] }
cliclack             = "0.3.6"
embed-commit         = { workspace = true }
heck                 = "0.5.0"
serde_json           = { workspace = true }
ucs04                = { workspace = true }
unionlabs-primitives = { workspace = true }
voyager-config       = { workspace = true }
voyager-core         = { workspace = true }
voyager-primitives   = { workspace = true }
voyager-rpc          = { workspace = true }

voyager-client-module-arbitrum               = { workspace = true }
voyager-client-module-bob                    = { workspace = true }
voyager-client-module-cometbls               = { workspace = true }
voyager-client-module-ethereum               = { workspace = true }
voyager-client-module-ethermint              = { workspace = true }
voyager-client-module-state-lens-ics23-ics23 = { workspace = true }
voyager-client-module-state-lens-ics23-mpt   = { workspace = true }
voyager-client-module-state-lens-ics23-smt   = { workspace = true }
voyager-client-module-sui                    = { workspace = true }
voyager-client-module-tendermint             = { workspace = true }

voyager-finality-module-arbitrum   = { workspace = true }
voyager-finality-module-bob        = { workspace = true }
voyager-finality-module-cometbls   = { workspace = true }
voyager-finality-module-ethereum   = { workspace = true }
voyager-finality-module-sui        = { workspace = true }
voyager-finality-module-tendermint = { workspace = true }

voyager-state-module-cosmos-sdk       = { workspace = true }
voyager-state-module-cosmos-sdk-union = { workspace = true }
voyager-state-module-ethereum         = { workspace = true }
voyager-state-module-sui              = { workspace = true }

voyager-proof-module-cosmos-sdk       = { workspace = true }
voyager-proof-module-cosmos-sdk-union = { workspace = true }
voyager-proof-module-ethereum         = { workspace = true }
voyager-proof-module-ethermint        = { workspace = true }
voyager-proof-module-sui              = { workspace = true }
